import React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faUserLarge } from "@fortawesome/free-solid-svg-icons";
import { faBriefcase } from "@fortawesome/free-solid-svg-icons";
import { faGraduationCap } from "@fortawesome/free-solid-svg-icons";
import { faStar } from "@fortawesome/free-solid-svg-icons";
const CVPreview = ({ formData }) => {
  const {
    firstName,
    lastName,
    wantedJobTitle,
    email,
    phone,
    address,
    city,
    postalCode,
    country,
    dateOfBirth,
    nationality,
    placeOfBirth,
    drivingLicense,
    professionalSummary,
    educationData,
    experienceData,
    languageData,
    skillData,
    referenceData,
    sectionData,
  } = formData;

  const formatDate = (date) => {
    if (!date) return "";
    const options = { month: "short", year: "numeric" };
    return new Date(date).toLocaleDateString("en-US", options);
  };

  // Function to format description with bullets
  const formatDescription = (description) => {
    // Return the HTML content generated by ReactQuill
    return <div dangerouslySetInnerHTML={{ __html: description }} />;
  };

  return (
    <div className="blank-sheet" id="cv-preview">
      <div className="cv-content">
        <div className="row align-items-center">
          <div className="cv-preview-container">
            <div className="row">
              <div className="col-12">
                {firstName && lastName && <h1>{`${firstName} ${lastName}`}</h1>}
              </div>
            </div>
            <div className="row">
              <div
                className="col-md-9"
                // style={{ borderRight: "2px solid lightblue" }}
                style={{
                  borderRight: `solid 2px ${
                    formData.color ? formData.color : "lightgray"
                  }`,
                }}
              >
                <div className="personal-info">
                  <div className="job-title-section">
                    {wantedJobTitle && (
                      <p>
                        <b>{wantedJobTitle}</b>
                      </p>
                    )}
                  </div>
                  <div className="row">
                    <div className="col-md-6">
                      {phone && <p className="m-0">{phone}</p>}
                    </div>
                    <div className="col-md-6 d-flex justify-content-end">
                      {email && <p className="m-0">{email}</p>}
                    </div>
                  </div>
                  <div className="job-title-section">
                    {(address || city || postalCode || country) && (
                      <p>
                        {address && `${address}, `}
                        {city && `${city}, `}
                        {postalCode && `${postalCode}, `}
                        {country}
                      </p>
                    )}
                  </div>
                  <div className="row">
                    <div className="col-md-6">
                      {dateOfBirth && (
                        <p className="flex-grow-1 m-0">
                          <b>Date of Birth: </b> {dateOfBirth}
                        </p>
                      )}
                      {nationality && (
                        <p className="flex-grow-1 m-0">
                          <b>Nationality: </b> {nationality}
                        </p>
                      )}
                    </div>
                    <div className="col-md-6">
                      {placeOfBirth && (
                        <p className="flex-grow-1 m-0 text-end">
                          <b>Place of Birth: </b> {placeOfBirth}
                        </p>
                      )}
                      {drivingLicense && (
                        <p className="flex-grow-1 m-0 text-end">
                          <b>Driving License: </b> {drivingLicense}
                        </p>
                      )}
                    </div>
                  </div>
                </div>

                <div className="professional-summary">
                  {professionalSummary && (
                    <>
                      <h2 className="big-title-temp">
                        <FontAwesomeIcon
                          icon={faUserLarge}
                          style={{
                            color: formData.color
                              ? formData.color
                              : "lightgray",
                          }}
                        />{" "}
                        Profile
                      </h2>
                      <div className="profile-content">
                        {professionalSummary}
                      </div>
                    </>
                  )}
                </div>

                <div className="education-section">
                  {educationData && educationData.length > 0 && (
                    <h2 className="big-title-temp">
                      <FontAwesomeIcon
                        icon={faGraduationCap}
                        // style={{ color: "lightblue" }}
                        style={{
                          color: formData.color ? formData.color : "lightgray",
                        }}
                      />{" "}
                      Education
                    </h2>
                  )}

                  {educationData?.map((education, index) => (
                    <div key={index} className="education-item">
                      <div className="row">
                        <div className="col">
                          <p className="p-0 m-0">
                            <span style={{ marginRight: "5px" }}>&#10146;</span>{" "}
                            <span>{education?.school}</span>
                          </p>
                        </div>
                        <div className="col text-end">
                          <p className="p-0 m-0">
                            {formatDate(education?.startDate)} -{" "}
                            {education?.endDate
                              ? formatDate(education.endDate)
                              : "Present"}
                          </p>
                        </div>
                      </div>
                      <div className="row" style={{ fontSize: "14px" }}>
                        <div className="col">
                          <p className="p-0 m-0">
                            <span>
                              <i>{education?.degree}</i>
                            </span>
                          </p>
                        </div>
                        <div className="col text-end">
                          <p className="p-0 m-0">
                            <span>
                              <i>{education?.city}</i>
                            </span>
                          </p>
                        </div>
                      </div>
                      <div className="description mb-2">
                        {formatDescription(education?.description)}
                      </div>
                    </div>
                  ))}
                </div>

                <div className="experience-section">
                  {experienceData && experienceData.length > 0 && (
                    <h2 className="big-title-temp">
                      <FontAwesomeIcon
                        icon={faBriefcase}
                        style={{
                          color: formData.color ? formData.color : "lightgray",
                        }}
                      />{" "}
                      Experience
                    </h2>
                  )}

                  {experienceData?.map((experience, index) => (
                    <div key={index} className="experience-item">
                      <div className="row mb-0">
                        <div className="col">
                          <p className="p-0 m-0">
                            <span style={{ marginRight: "5px" }}>&#10146;</span>{" "}
                            {experience?.jobTitle},{" "}
                            <span>{experience?.employer}</span>
                          </p>
                        </div>
                        <div className="col text-end">
                          <p className="p-0 m-0">
                            {formatDate(experience?.startDate)} -{" "}
                            {experience?.endDate
                              ? formatDate(experience.endDate)
                              : "Present"}
                          </p>
                        </div>
                      </div>
                      <div
                        className="row"
                        style={{ margin: "0", fontSize: "14px" }}
                      >
                        <div className="col text-end ">
                          <p className="city p-0 m-0">
                            <span>
                              {" "}
                              <i>{experience?.city}</i>
                            </span>
                          </p>
                        </div>
                      </div>
                      <div className="description mb-2">
                        {formatDescription(experience?.description)}
                      </div>
                    </div>
                  ))}
                </div>

                <div className="sections-section">
                  {sectionData?.map((section, index) => (
                    <div key={index} className="section-item">
                      <h2 className="big-title-temp">
                        <FontAwesomeIcon
                          icon={faStar}
                          style={{
                            color: formData.color
                              ? formData.color
                              : "lightgray",
                          }}
                        />{" "}
                        {section.name}
                      </h2>
                      <p>{section.content}</p>
                    </div>
                  ))}
                </div>
              </div>

              <div className="col-md-3">
                <div className="languages-section">
                  {languageData && languageData.length > 0 && (
                    <h2 className="big-title-temp">Languages</h2>
                  )}
                  <div className="row">
                    {languageData?.map((language, index) => (
                      <div key={index} className="col-12">
                        <div key={index} className="language-item">
                          <p className="p-0 m-0">
                            {" "}
                            <span>
                              <b>{language?.language}</b>,{" "}
                              <span>{language?.proficiency}</span>
                            </span>
                          </p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="skills-section">
                  {skillData && skillData.length > 0 && (
                    <h2 className="big-title-temp mt-4">Skills</h2>
                  )}

                  <div className="row">
                    {skillData?.map((skill, index) => (
                      <div key={index} className="col-12">
                        <div className="skill-item">
                          <p className="p-0 m-0">
                            <span>
                              <b>{skill?.name}</b>, <span>{skill?.level}</span>
                            </span>
                          </p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="references-section">
                  {referenceData && referenceData.length > 0 && (
                    <h2 className="big-title-temp mt-4">References</h2>
                  )}

                  {referenceData?.map((reference, index) => (
                    <div key={index} className="reference-item">
                      <div className="row">
                        <div className="col">
                          <p className="p-0 m-0">
                            <b>{reference?.fullName}</b>
                          </p>
                          <p className="p-0 m-0">{reference?.company}</p>
                          <p className="p-0 m-0">{reference?.email}</p>
                          <p className="p-0 m-0">{reference?.phone}</p>
                        </div>
                      </div>

                      <div className="description mb-2">
                        {reference?.description}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CVPreview;
