import React from "react";

const CVPreview = ({ formData }) => {
  const {
    firstName,
    lastName,
    wantedJobTitle,
    email,
    phone,
    address,
    city,
    postalCode,
    country,
    dateOfBirth,
    nationality,
    placeOfBirth,
    drivingLicense,
    professionalSummary,
    educationData,
    experienceData,
    languageData,
    skillData,
    referenceData,
    sectionData,
  } = formData;

  // Function to format the date as month abbreviation followed by the year (e.g., "Aug 2022")
  const formatDate = (date) => {
    if (!date) return "";
    const options = { month: "short", year: "numeric" };
    return new Date(date).toLocaleDateString("en-US", options);
  };

  // Function to format description with bullets
  const formatDescription = (description) => {
    // Return the HTML content generated by ReactQuill
    return <div dangerouslySetInnerHTML={{ __html: description }} />;
  };

  return (
    <div className="blank-sheet" id="cv-preview">
      <div className="cv-content">
        <div className="row align-items-center">
          <div className="cv-preview-container">
            <div className="personal-info">
              <div className="name-section">
                {firstName && lastName && <h1>{`${firstName} ${lastName}`}</h1>}
              </div>

              <div className="row">
                <div className="col-md-6">
                  <div className="additional-info d-flex flex-column">
                    {placeOfBirth && (
                      <p className="flex-grow-1 m-0">
                        <b>Place of Birth: </b> {placeOfBirth}
                      </p>
                    )}
                    {drivingLicense && (
                      <p className="flex-grow-1 m-0">
                        <b>Driving License: </b> {drivingLicense}
                      </p>
                    )}
                  </div>
                </div>
                <div className="col-md-6">
                  <div className="additional-info d-flex flex-column">
                    {dateOfBirth && (
                      <p className="flex-grow-1 m-0 text-end">
                        <b>Date of Birth: </b> {dateOfBirth}
                      </p>
                    )}
                    {nationality && (
                      <p className="flex-grow-1 m-0 text-end">
                        <b>Nationality: </b> {nationality}
                      </p>
                    )}
                  </div>
                </div>
              </div>

              <div className="job-title-section">
                {wantedJobTitle && (
                  <p>
                    <b>{wantedJobTitle}</b>
                  </p>
                )}
              </div>
              <div className="job-title-section">
                {(address || city || postalCode || country) && (
                  <p>
                    {address && `${address}, `}
                    {city && `${city}, `}
                    {postalCode && `${postalCode}, `}
                    {country}
                  </p>
                )}
              </div>
              <div className="row align-items-center">
                <div className="col-md-6">
                  {phone && <p className="m-0">{phone}</p>}
                </div>
                <div className="col-md-6 d-flex justify-content-end">
                  {email && <p className="m-0">{email}</p>}
                </div>
              </div>
            </div>
            <div className="professional-summary">
              {professionalSummary && (
                <>
                  <h2
                    className="big-title"
                    style={{
                      color: "#555",
                      borderBottom: `solid 2px ${
                        formData.color ? formData.color : "lightgray"
                      }`,
                    }}
                  >
                    Profile
                  </h2>
                  <div className="profile-content">{professionalSummary}</div>
                </>
              )}
            </div>
            {/* Education section */}
            {educationData && educationData.length > 0 && (
              <div className="education-section">
                <h2
                  className="big-title"
                  style={{
                    color: "#555",
                    borderBottom: `solid 2px ${
                      formData.color ? formData.color : "lightgray"
                    }`,
                  }}
                >
                  Education
                </h2>

                {educationData?.map((education, index) => (
                  <div key={index} className="education-item">
                    {/* First Row */}
                    <div className="row">
                      <div className="col">
                        <p className="p-0 m-0">
                          <span
                            style={{
                              marginRight: "5px",
                              color: formData.color ? formData.color : "black",
                            }}
                          >
                            &#x2756;
                          </span>{" "}
                          {/* Custom bullet */}
                          <span>
                            <b>{education?.school}</b>
                          </span>
                        </p>
                      </div>

                      <div className="col text-end">
                        <p className="p-0 m-0">
                          {formatDate(education?.startDate)} -{" "}
                          {education?.endDate
                            ? formatDate(education.endDate)
                            : "Present"}
                        </p>
                      </div>
                    </div>
                    {/* Second Row */}
                    <div className="row" style={{ fontSize: "14px" }}>
                      <div className="col">
                        <p className="p-0 m-0">
                          <span>
                            <i>{education?.degree}</i>
                          </span>
                        </p>
                      </div>
                      <div className="col text-end">
                        <p className="p-0 m-0">
                          <span>
                            <i>{education?.city}</i>
                          </span>
                        </p>
                      </div>
                    </div>

                    {/* Description */}
                    <div className="description mb-2">
                      {formatDescription(education?.description)}
                    </div>
                  </div>
                ))}
              </div>
            )}

            {/* Experience section */}
            {experienceData && experienceData.length > 0 && (
              <div className="experience-section">
                <h2
                  className="big-title"
                  style={{
                    color: "#555",
                    borderBottom: `solid 2px ${
                      formData.color ? formData.color : "lightgray"
                    }`,
                  }}
                >
                  Experience
                </h2>
                {experienceData?.map((experience, index) => (
                  <div key={index} className="experience-item">
                    {/* First Row */}
                    <div className="row mb-0">
                      <div className="col">
                        <p className="p-0 m-0">
                          <span
                            style={{
                              marginRight: "5px",
                              color: formData.color ? formData.color : "black",
                            }}
                          >
                            &#x2756;
                          </span>{" "}
                          {/* Custom bullet */}
                          <b>{experience?.jobTitle}</b>,{" "}
                          <span>
                            <b>{experience?.employer}</b>
                          </span>
                        </p>
                      </div>
                      <div className="col text-end">
                        <p className="p-0 m-0">
                          {formatDate(experience?.startDate)} -{" "}
                          {experience?.endDate
                            ? formatDate(experience.endDate)
                            : "Present"}
                        </p>
                      </div>
                    </div>
                    {/* Second Row */}
                    <div
                      className="row"
                      style={{ margin: "0", fontSize: "14px" }}
                    >
                      <div className="col text-end ">
                        <p className="city p-0 m-0">
                          <span>
                            {" "}
                            <i>{experience?.city}</i>
                          </span>
                        </p>
                      </div>
                    </div>
                    {/* Description */}
                    <div className="description mb-2">
                      {formatDescription(experience?.description)}
                    </div>
                  </div>
                ))}
              </div>
            )}

            {/* Languages section */}
            <div className="languages-section">
              {languageData && languageData.length > 0 && (
                <h2
                  className="big-title"
                  style={{
                    color: "#555",
                    borderBottom: `solid 2px ${
                      formData.color ? formData.color : "lightgray"
                    }`,
                  }}
                >
                  Languages
                </h2>
              )}
              <div className="row">
                {languageData?.map((language, index) => (
                  <div key={index} className="col-md-3">
                    <div key={index} className="language-item">
                      <p className="p-0 m-0">
                        <span
                          style={{
                            marginRight: "5px",
                            color: formData.color ? formData.color : "black",
                          }}
                        >
                          &#x2756;
                        </span>{" "}
                        {/* Custom bullet */}
                        <span>
                          <b>{language?.language}</b>,{" "}
                          <span>{language?.proficiency}</span>
                        </span>
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Skills section */}
            <div className="skills-section">
              {skillData && skillData.length > 0 && (
                <h2
                  className="big-title"
                  style={{
                    color: "#555",
                    borderBottom: `solid 2px ${
                      formData.color ? formData.color : "lightgray"
                    }`,
                  }}
                >
                  Skills
                </h2>
              )}
              <div className="row">
                {skillData?.map((skill, index) => (
                  <div key={index} className="col-md-4">
                    <div className="skill-item">
                      <p className="p-0 m-0">
                        <span
                          style={{
                            marginRight: "5px",
                            color: formData.color ? formData.color : "black",
                          }}
                        >
                          &#x2756;
                        </span>
                        <span>
                          {/* <span style={{ color: "blue" }}>  */}
                          <b>{skill?.name}</b>, <span>{skill?.level}</span>
                        </span>
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* References section */}
            <div className="references-section">
              {referenceData && referenceData.length > 0 && (
                <h2
                  className="big-title"
                  style={{
                    color: "#555",
                    borderBottom: `solid 2px ${
                      formData.color ? formData.color : "lightgray"
                    }`,
                  }}
                >
                  References
                </h2>
              )}
              {referenceData?.map((reference, index) => (
                <div key={index} className="reference-item">
                  {/* First Row */}
                  <div className="row">
                    <div className="col">
                      <p className="p-0 m-0">
                        <span
                          style={{
                            marginRight: "5px",
                            color: formData.color ? formData.color : "black",
                          }}
                        >
                          &#x2756;
                        </span>
                        {/* Custom bullet */}
                        <b>{reference.fullName}</b>
                      </p>
                    </div>
                    <div className="col text-end">
                      <p className="p-0 m-0">{reference.email}</p>
                    </div>
                  </div>
                  {/* Second Row */}
                  <div className="row">
                    <div className="col">
                      <p className="p-0 m-0">{reference.company}</p>
                    </div>
                    <div className="col text-end">
                      <p className="p-0 m-0">{reference.phone}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {/* Sections section */}
            <div className="sections-section">
              {sectionData?.map((section, index) => (
                <div key={index} className="section-item">
                  <h2
                    className="big-title"
                    style={{
                      color: "#555",
                      borderBottom: `solid 2px ${
                        formData.color ? formData.color : "lightgray"
                      }`,
                    }}
                  >
                    {section.name}
                  </h2>
                  <p>{section.content}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CVPreview;
